import Link from "next/link";
import { loadState } from "@/lib/loadState";
import { HeadlineKPIs } from "@/components/HeadlineKPIs";
import { HeroChart } from "@/components/HeroChart";
import { TrajectoryChart } from "@/components/TrajectoryChart";
import { SmallMultiples } from "@/components/SmallMultiples";
import { SeeingAxisChart } from "@/components/SeeingAxisChart";
import { SizeAxisChart } from "@/components/SizeAxisChart";
import { CoverageMatrix } from "@/components/CoverageMatrix";
import { SystemStatus } from "@/components/SystemStatus";
import { Phase4Card } from "@/components/Phase4Card";
import { CrashLog } from "@/components/CrashLog";
import { TaskTable } from "@/components/TaskTable";

export default async function Home() {
  const state = await loadState();
  return (
    <main className="mx-auto max-w-[1200px] px-4 sm:px-6 py-6 space-y-5">
      {/* compact one-line header */}
      <header className="flex items-baseline justify-between gap-4 flex-wrap">
        <div className="flex items-baseline gap-3">
          <span className="text-base font-medium tracking-tight text-zinc-900">
            SESL
          </span>
          <span className="text-xs text-zinc-500">
            Self-Evolve Scaling Laws
          </span>
        </div>
        <div className="flex items-center gap-3">
          <Link
            href="./findings/"
            className="text-[11px] px-2 py-1 rounded-md bg-zinc-900 text-white hover:bg-zinc-700"
          >
            Findings · 初步结果 →
          </Link>
          <div className="flex items-center gap-2 text-[10px] tabular-nums text-zinc-400 font-mono">
            <span>{state.generated_at_iso}</span>
            <span>·</span>
            <span>git {state.git_sha}</span>
          </div>
        </div>
      </header>

      {/* KPIs — three tiles */}
      <HeadlineKPIs curves={state.xt_curves} />

      {/* Per-task small multiples — Codex Rec C, the HEADLINE evidence.
          Each panel = one task with its own clean envelope; no cross-task
          interference. */}
      <SmallMultiples trajectories={state.trajectories ?? []} minRuns={3} />

      {/* Aggregated per-run trajectories — Kaplan-style multi-curve view
          across all tasks. Useful as a "summary" but the small-multiples
          above is the headline. */}
      <TrajectoryChart
        trajectories={state.trajectories ?? []}
        envelope={state.envelope ?? []}
        envelopeByClass={state.envelope_by_class ?? {}}
      />

      {/* Aggregate cross-task hero chart */}
      <HeroChart curves={state.xt_curves} />

      {/* Two supporting analyses */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <SeeingAxisChart curves={state.xt_curves} />
        <SizeAxisChart curves={state.xt_curves} />
      </div>

      {/* Operational details — collapsed */}
      <details className="bg-white border border-zinc-200 rounded-xl p-4 group">
        <summary className="cursor-pointer text-xs uppercase tracking-wider text-zinc-500 list-none flex items-center gap-2">
          <span className="inline-block w-2 h-2 rounded-full bg-emerald-500" />
          Operational details
          <span className="ml-auto text-[10px] text-zinc-400 group-open:hidden">
            click to expand
          </span>
        </summary>
        <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-3">
          <SystemStatus
            servers={state.servers}
            grids={state.grids}
            counts={state.run_counts}
          />
          <CoverageMatrix coverage={state.coverage} />
          <TaskTable headline={state.tasks_headline} />
          <Phase4Card items={state.phase4_pending} />
          <div className="md:col-span-2">
            <CrashLog events={state.events} />
          </div>
        </div>
        {state.xt_dropped_saturated_tasks.length > 0 ? (
          <p className="mt-3 text-[10px] text-zinc-400 font-mono">
            saturated probes excluded:{" "}
            {state.xt_dropped_saturated_tasks.join(", ")}
          </p>
        ) : null}
      </details>

      <footer className="text-center text-[10px] text-zinc-400 font-mono pt-2 pb-8">
        bundle auto-generated by scripts/build_site_data.py · git {state.git_sha}
      </footer>
    </main>
  );
}
