import { loadState } from "@/lib/loadState";
import { SystemStatus } from "@/components/SystemStatus";
import { ScalingPanel } from "@/components/ScalingChart";
import { CoverageMatrix } from "@/components/CoverageMatrix";
import { TaskTable } from "@/components/TaskTable";
import { Phase4Card } from "@/components/Phase4Card";
import { CrashLog } from "@/components/CrashLog";

export default async function Home() {
  const state = await loadState();
  return (
    <main className="mx-auto max-w-5xl px-4 sm:px-6 py-10 space-y-6">
      <header className="space-y-3">
        <h1 className="text-2xl sm:text-3xl font-semibold tracking-tight">
          SESL — Self-Evolve Scaling Laws
        </h1>
        <p className="text-sm text-[color:var(--muted-foreground)] leading-relaxed">
          {state.project_summary}
        </p>
        <div className="flex flex-wrap gap-2 text-xs">
          <span className="badge">
            updated{" "}
            <span className="mono">{state.generated_at_iso}</span>
          </span>
          <span className="badge mono">git {state.git_sha}</span>
          <a
            className="badge"
            href="https://github.com/Imbernoulli/sesl-website"
            target="_blank"
            rel="noreferrer"
          >
            site source
          </a>
        </div>
      </header>

      <SystemStatus
        servers={state.servers}
        grids={state.grids}
        counts={state.run_counts}
      />

      <ScalingPanel
        curves={state.xt_curves}
        dropped={state.xt_dropped_saturated_tasks}
      />

      <CoverageMatrix coverage={state.coverage} />

      <TaskTable headline={state.tasks_headline} />

      <div className="grid md:grid-cols-2 gap-6">
        <Phase4Card items={state.phase4_pending} />
        <CrashLog events={state.events} />
      </div>

      <footer className="pt-4 pb-12 text-center text-xs text-[color:var(--muted-foreground)]">
        Bundle generated by{" "}
        <span className="mono">scripts/build_site_data.py</span> on each push to
        the private <span className="mono">sesl-dev</span> repo. Source code +
        raw runs/ live in that private mirror.
      </footer>
    </main>
  );
}
