"use client";

import { useState } from "react";
import Link from "next/link";
import type { ScalingLaws } from "@/lib/types";
import { findingsCopy, type Lang } from "@/lib/findings";

// Static figure paths — generated by scripts/render_findings_figures.py
// Next.js basePath is added by the env at build time so the same paths
// work on the dev box and on GitHub Pages.
const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const FIG_DIR = `${BASE}/figures/findings`;

function Figure({
  src,
  alt,
  title,
  caption,
  reading,
}: {
  src: string;
  alt: string;
  title: string;
  caption: string;
  reading: string;
}) {
  return (
    <section className="bg-white border border-zinc-200 rounded-2xl shadow-sm p-6 space-y-3">
      <header>
        <h2 className="text-base font-medium text-zinc-900">{title}</h2>
        <p className="text-sm text-zinc-600 mt-1 leading-relaxed">{caption}</p>
      </header>
      <div className="bg-white rounded-lg overflow-hidden">
        {/* Plain <img>: figure files are SVG so they scale crisply. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={src} alt={alt} className="w-full h-auto" />
      </div>
      <p className="text-sm text-zinc-600 leading-relaxed">{reading}</p>
    </section>
  );
}

export function FindingsView({
  scalingLaws,
  generatedAtIso,
  gitSha,
}: {
  scalingLaws: ScalingLaws | null;
  generatedAtIso: string;
  gitSha: string;
}) {
  const [lang, setLang] = useState<Lang>("en");
  const copy = findingsCopy[lang];

  if (!scalingLaws) {
    return (
      <main className="mx-auto max-w-[1200px] px-4 sm:px-6 py-6">
        <h1 className="text-xl font-medium">{copy.pageTitle}</h1>
        <p className="text-sm text-zinc-500 mt-2">
          scaling_laws.json not built yet — run <code>scripts/scaling_laws.py</code>.
        </p>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-[1200px] px-4 sm:px-6 py-6 space-y-5">
      <header className="flex items-baseline justify-between gap-4 flex-wrap">
        <div className="flex items-baseline gap-3">
          <Link href="./" className="text-xs text-zinc-500 hover:text-zinc-800">
            {copy.backToDashboard}
          </Link>
          <span className="text-base font-medium tracking-tight text-zinc-900">SESL</span>
          <span className="text-xs text-zinc-500">{copy.pageTitle}</span>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 text-[10px] tabular-nums text-zinc-400 font-mono">
            <span>{copy.asOf}</span>
            <span>{generatedAtIso}</span>
            <span>·</span>
            <span>git {gitSha}</span>
            <span>·</span>
            <span>{scalingLaws.n_runs_indexed} runs</span>
          </div>
          <div className="inline-flex border border-zinc-200 rounded-md overflow-hidden text-xs">
            <button
              onClick={() => setLang("en")}
              className={`px-2 py-1 ${lang === "en" ? "bg-zinc-900 text-white" : "bg-white text-zinc-600 hover:bg-zinc-50"}`}
            >
              {copy.langEN}
            </button>
            <button
              onClick={() => setLang("zh")}
              className={`px-2 py-1 ${lang === "zh" ? "bg-zinc-900 text-white" : "bg-white text-zinc-600 hover:bg-zinc-50"}`}
            >
              {copy.langZH}
            </button>
          </div>
        </div>
      </header>

      <div className="bg-white border border-zinc-200 rounded-2xl shadow-sm p-6 space-y-3">
        <h1 className="text-xl font-medium text-zinc-900 tracking-tight">{copy.pageTitle}</h1>
        <p className="text-sm text-zinc-600 leading-relaxed">{copy.pageSubtitle}</p>
        <h3 className="text-sm uppercase tracking-wider text-zinc-500 pt-1">{copy.setupTitle}</h3>
        <p className="text-sm text-zinc-600 leading-relaxed">{copy.setupBody}</p>
        <h3 className="text-sm uppercase tracking-wider text-zinc-500 pt-1">{copy.axisMapTitle}</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="text-zinc-500 border-b border-zinc-200">
                <th className="text-left font-normal py-1.5">Chinchilla 2203.15556</th>
                <th className="text-left font-normal py-1.5">SESL</th>
                <th className="text-left font-normal py-1.5">note</th>
              </tr>
            </thead>
            <tbody>
              {copy.axisMapRows.map((r, i) => (
                <tr key={i} className="border-b border-zinc-100">
                  <td className="py-1.5 text-zinc-700">{r.chinchilla}</td>
                  <td className="py-1.5 text-zinc-700 font-mono">{r.sesl}</td>
                  <td className="py-1.5 text-zinc-500">{r.note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <Figure
        src={`${FIG_DIR}/fig1.svg`}
        alt="Figure 1 — K-axis scaling law per (model, feedback)"
        title={copy.fig1Title}
        caption={copy.fig1Caption}
        reading={copy.fig1Reading}
      />
      <Figure
        src={`${FIG_DIR}/fig2.svg`}
        alt="Figure 2 — per-run trajectories with compute-optimal envelope"
        title={copy.fig2Title}
        caption={copy.fig2Caption}
        reading={copy.fig2Reading}
      />
      <Figure
        src={`${FIG_DIR}/fig3.svg`}
        alt="Figure 3 — IsoFLOP comparison across proposers"
        title={copy.fig3Title}
        caption={copy.fig3Caption}
        reading={copy.fig3Reading}
      />
      <Figure
        src={`${FIG_DIR}/fig4.svg`}
        alt="Figure 4 — Approach 3 parametric fit validation"
        title={copy.fig4Title}
        caption={copy.fig4Caption}
        reading={copy.fig4Reading}
      />
      <Figure
        src={`${FIG_DIR}/appA_alpha_distribution.svg`}
        alt="Appendix A — cross-task α distribution"
        title={copy.appATitle}
        caption={copy.appACaption}
        reading=""
      />

      <section className="bg-white border border-zinc-200 rounded-2xl shadow-sm p-6">
        <h3 className="text-sm uppercase tracking-wider text-zinc-500 mb-3">{copy.caveatsTitle}</h3>
        <ul className="space-y-2 text-sm text-zinc-700 leading-relaxed">
          {copy.caveats.map((l, i) => (
            <li key={i} className="flex gap-2">
              <span className="text-zinc-400 select-none">•</span>
              <span>{l}</span>
            </li>
          ))}
        </ul>
      </section>

      <footer className="text-center text-[10px] text-zinc-400 font-mono pt-2 pb-8">
        {scalingLaws.n_runs_indexed} indexed runs · {scalingLaws.K_per_task?.length ?? 0} per-task K fits ·{" "}
        {scalingLaws.joint_NK?.fits?.length ?? 0} joint (N,K) fits · figures generated by{" "}
        <code>scripts/render_findings_figures.py</code> · git {gitSha}
      </footer>
    </main>
  );
}
